"""Constants for ha_bigbox."""

from logging import Logger, getLogger

from homeassistant.backports.enum import StrEnum

LOGGER: Logger = getLogger(__package__)

DOMAIN = "ha_bigbox"
ATTRIBUTION = "Data provided by http://jsonplaceholder.typicode.com/"


class Item(StrEnum):
    """Key used across library."""

    IS_BIGBOX_LOCKED = "IsBigBoxLocked"
    IS_BIGBOX_IN_ATTRACT_MODE = "IsBigBoxInAttractMode"
    IS_BIGBOX = "IsBigBox"
    IS_PREMIUM = "IsPremium"
    BIGBOX_CURRENT_THEME = "BigBoxCurrentTheme"


class ApiUrl(StrEnum):
    """Key used across api."""

    ACTIVITY_LOG_ENTRIES = "/System/ActivityLog/Entries"

    """/StateManager"""
    STATE_MANAGER = "/StateManager"
    IS_IN_GAME = "/StateManager/IsInGame"
    IS_BIGBOX_LOCKED = "/StateManager/IsBigBoxLocked"
    IS_BIGBOX_IN_ATTRACT_MODE = "/StateManager/IsBigBoxInAttractMode"
    IS_BIGBOX = "/StateManager/IsBigBox"
    IS_PREMIUM = "/StateManager/IsPremium"
    BIGBOX_CURRENT_THEME = "/StateManager/BigBoxCurrentTheme"

    """/SelectedGame"""
    SELECTED_GAME = "/SelectedGame"
    AGGRESSIVE_WINDOW_HIDING = "/SelectedGame/AggressiveWindowHiding"
    APPLICATION_PATH = "/SelectedGame/ApplicationPath"
    BACKGROUND_IMAGE_PATH = "/SelectedGame/BackgroundImagePath"
    BACK_IMAGE_PATH = "/SelectedGame/BackImagePath"
    BOX_3D_IMAGE_PATH = "/SelectedGame/Box3DImagePath"
    BROKEN = "/SelectedGame/Broken"
    CART_3D_IMAGE_PATH = "/SelectedGame/Cart3DImagePath"
    CART_BACK_IMAGE_PATH = "/SelectedGame/CartBackImagePath"
    CART_FRONT_IMAGE_PATH = "/SelectedGame/CartFrontImagePath"
    CLEAR_LOGO_IMAGE_PATH = "/SelectedGame/ClearLogoImagePath"
    CLONE_OF = "/SelectedGame/CloneOf"
    COMMAND_LINE = "/SelectedGame/CommandLine"
    COMMUNITY_OR_LOCAL_STAR_RATING = "/SelectedGame/CommunityOrLocalStarRating"
    COMMUNITY_STAR_RATING = "/SelectedGame/CommunityStarRating"
    COMMUNITY_STAR_RATING_TOTAL_VOTES = "/SelectedGame/CommunityStarRatingTotalVotes"
    COMPLETED = "/SelectedGame/Completed"
    CONFIGURATION_COMMAND_LINE = "/SelectedGame/ConfigurationCommandLine"
    CONFIGURATION_PATH = "/SelectedGame/ConfigurationPath"
    DATE_ADDED = "/SelectedGame/DateAdded"
    DATE_MODIFIED = "/SelectedGame/DateModified"
    DETAILS_WITHOUT_PLATFORM = "/SelectedGame/DetailsWithoutPlatform"
    DETAILS_WITH_PLATFORM = "/SelectedGame/DetailsWithPlatform"
    DEVELOPER = "/SelectedGame/Developer"
    DEVELOPERS = "/SelectedGame/Developers"
    DISABLE_SHUTDOWN_SCREEN = "/SelectedGame/DisableShutdownScreen"
    DOS_BOX_CONFIGURATION_PATH = "/SelectedGame/DosBoxConfigurationPath"
    EMULATOR_ID = "/SelectedGame/EmulatorId"
    FAVORITE = "/SelectedGame/Favorite"
    FRONT_IMAGE_PATH = "/SelectedGame/FrontImagePath"
    GENRES = "/SelectedGame/Genres"
    GENRES_STRING = "/SelectedGame/GenresString"
    HIDE = "/SelectedGame/Hide"
    HIDE_ALL_NON_EXCLUSIVE_FULLSCREEN_WINDOWS = (
        "/SelectedGame/HideAllNonExclusiveFullscreenWindows"
    )
    HIDE_MOUSE_CURSOR_IN_GAME = "/SelectedGame/HideMouseCursorInGame"
    ID = "/SelectedGame/Id"
    INSTALLED = "/SelectedGame/Installed"
    LAST_PLAYED_DATE = "/SelectedGame/LastPlayedDate"
    LAUNCH_BOX_DB_ID = "/SelectedGame/LaunchBoxDbId"
    MANUAL_PATH = "/SelectedGame/ManualPath"
    MARQUEE_IMAGE_PATH = "/SelectedGame/MarqueeImagePath"
    MAX_PLAYERS = "/SelectedGame/MaxPlayers"
    MUSIC_PATH = "/SelectedGame/MusicPath"
    NOTES = "/SelectedGame/Notes"
    OVERRIDE_DEFAULT_STARTUP_SCREEN_SETTINGS = (
        "/SelectedGame/OverrideDefaultStartupScreenSettings"
    )
    PLATFORM = "/SelectedGame/Platform"
    PLATFORM_CLEAR_LOGO_IMAGE_PATH = "/SelectedGame/PlatformClearLogoImagePath"
    PLAY_COUNT = "/SelectedGame/PlayCount"
    PLAY_MODE = "/SelectedGame/PlayMode"
    PLAY_MODES = "/SelectedGame/PlayModes"
    PLAY_TIME = "/SelectedGame/PlayTime"
    PORTABLE = "/SelectedGame/Portable"
    PUBLISHER = "/SelectedGame/Publisher"
    PUBLISHERS = "/SelectedGame/Publishers"
    RATING = "/SelectedGame/Rating"
    RATING_IMAGE = "/SelectedGame/RatingImage"
    REGION = "/SelectedGame/Region"
    RELEASE_DATE = "/SelectedGame/ReleaseDate"
    RELEASE_TYPE = "/SelectedGame/ReleaseType"
    RELEASE_YEAR = "/SelectedGame/ReleaseYear"
    ROOT_FOLDER = "/SelectedGame/RootFolder"
    SCREENSHOT_IMAGE_PATH = "/SelectedGame/ScreenshotImagePath"
    SCUMM_VM_ASPECT_CORRECTION = "/SelectedGame/ScummVmAspectCorrection"
    SCUMM_VM_FULLSCREEN = "/SelectedGame/ScummVmFullscreen"
    SCUMM_VM_GAME_DATA_FOLDER_PATH = "/SelectedGame/ScummVmGameDataFolderPath"
    SCUMM_VM_GAME_TYPE = "/SelectedGame/ScummVmGameType"
    SERIES = "/SelectedGame/Series"
    SERIES_VALUES = "/SelectedGame/SeriesValues"
    SHOW_BACK = "/SelectedGame/ShowBack"
    SORT_TITLE = "/SelectedGame/SortTitle"
    SORT_TITLE_OR_TITLE = "/SelectedGame/SortTitleOrTitle"
    SOURCE = "/SelectedGame/Source"
    STAR_RATING = "/SelectedGame/StarRating"
    STAR_RATING_FLOAT = "/SelectedGame/StarRatingFloat"
    STARTUP_LOAD_DELAY = "/SelectedGame/StartupLoadDelay"
    STATUS = "/SelectedGame/Status"
    THEME_VIDEO_PATH = "/SelectedGame/ThemeVideoPath"
    TITLE = "/SelectedGame/Title"
    USE_DOS_BOX = "/SelectedGame/UseDosBox"
    USE_SCUMM_VM = "/SelectedGame/UseScummVm"
    USE_STARTUP_SCREEN = "/SelectedGame/UseStartupScreen"
    VERSION = "/SelectedGame/Version"
    VIDEO_PATH = "/SelectedGame/VideoPath"
    VIDEO_URL = "/SelectedGame/VideoUrl"
    WIKIPEDIA_ID = "/SelectedGame/WikipediaId"
    WIKIPEDIA_URL = "/SelectedGame/WikipediaUrl"

    """/SelectedGames"""
    """
    SELECTED_GAMES = "/SelectedGames"
    AGGRESSIVE_WINDOW_HIDING = "/SelectedGames/AggressiveWindowHiding"
    APPLICATION_PATH = "/SelectedGames/ApplicationPath"
    BACKGROUND_IMAGE_PATH = "/SelectedGames/BackgroundImagePath"
    BACK_IMAGE_PATH = "/SelectedGames/BackImagePath"
    BOX_3D_IMAGE_PATH = "/SelectedGames/Box3DImagePath"
    BROKEN = "/SelectedGames/Broken"
    CART_3D_IMAGE_PATH = "/SelectedGames/Cart3DImagePath"
    CART_BACK_IMAGE_PATH = "/SelectedGames/CartBackImagePath"
    CART_FRONT_IMAGE_PATH = "/SelectedGames/CartFrontImagePath"
    CLEAR_LOGO_IMAGE_PATH = "/SelectedGames/ClearLogoImagePath"
    CLONE_OF = "/SelectedGames/CloneOf"
    COMMAND_LINE = "/SelectedGames/CommandLine"
    COMMUNITY_OR_LOCAL_STAR_RATING = "/SelectedGames/CommunityOrLocalStarRating"
    COMMUNITY_STAR_RATING = "/SelectedGames/CommunityStarRating"
    COMMUNITY_STAR_RATING_TOTAL_VOTES = "/SelectedGames/CommunityStarRatingTotalVotes"
    COMPLETED = "/SelectedGames/Completed"
    CONFIGURATION_COMMAND_LINE = "/SelectedGames/ConfigurationCommandLine"
    CONFIGURATION_PATH = "/SelectedGames/ConfigurationPath"
    DATE_ADDED = "/SelectedGames/DateAdded"
    DATE_MODIFIED = "/SelectedGames/DateModified"
    DETAILS_WITHOUT_PLATFORM = "/SelectedGames/DetailsWithoutPlatform"
    DETAILS_WITH_PLATFORM = "/SelectedGames/DetailsWithPlatform"
    DEVELOPER = "/SelectedGames/Developer"
    DEVELOPERS = "/SelectedGames/Developers"
    DISABLE_SHUTDOWN_SCREEN = "/SelectedGames/DisableShutdownScreen"
    DOS_BOX_CONFIGURATION_PATH = "/SelectedGames/DosBoxConfigurationPath"
    EMULATOR_ID = "/SelectedGames/EmulatorId"
    FAVORITE = "/SelectedGames/Favorite"
    FRONT_IMAGE_PATH = "/SelectedGames/FrontImagePath"
    GENRES = "/SelectedGames/Genres"
    GENRES_STRING = "/SelectedGames/GenresString"
    HIDE = "/SelectedGames/Hide"
    HIDE_ALL_NONEX_FS_WINDOWS = "/SelectedGames/HideAllNonExclusiveFullscreenWindows"
    HIDE_MOUSE_CURSOR_IN_GAME = "/SelectedGames/HideMouseCursorInGame"
    ID = "/SelectedGames/Id"
    INSTALLED = "/SelectedGames/Installed"
    LAST_PLAYED_DATE = "/SelectedGames/LastPlayedDate"
    LAUNCH_BOX_DB_ID = "/SelectedGames/LaunchBoxDbId"
    MANUAL_PATH = "/SelectedGames/ManualPath"
    MARQUEE_IMAGE_PATH = "/SelectedGames/MarqueeImagePath"
    MAX_PLAYERS = "/SelectedGames/MaxPlayers"
    MUSIC_PATH = "/SelectedGames/MusicPath"
    NOTES = "/SelectedGames/Notes"
    OVERRIDE_START_SCREEN_SET = "/SelectedGames/OverrideDefaultStartupScreenSettings"
    PLATFORM = "/SelectedGames/Platform"
    PLATFORM_CLEAR_LOGO_IMAGE_PATH = "/SelectedGames/PlatformClearLogoImagePath"
    PLAY_COUNT = "/SelectedGames/PlayCount"
    PLAY_MODE = "/SelectedGames/PlayMode"
    PLAY_MODES = "/SelectedGames/PlayModes"
    PLAY_TIME = "/SelectedGames/PlayTime"
    PORTABLE = "/SelectedGames/Portable"
    PUBLISHER = "/SelectedGames/Publisher"
    PUBLISHERS = "/SelectedGames/Publishers"
    RATING = "/SelectedGames/Rating"
    RATING_IMAGE = "/SelectedGames/RatingImage"
    REGION = "/SelectedGames/Region"
    RELEASE_DATE = "/SelectedGames/ReleaseDate"
    RELEASE_TYPE = "/SelectedGames/ReleaseType"
    RELEASE_YEAR = "/SelectedGames/ReleaseYear"
    ROOT_FOLDER = "/SelectedGames/RootFolder"
    SCREENSHOT_IMAGE_PATH = "/SelectedGames/ScreenshotImagePath"
    SCUMM_VM_ASPECT_CORRECTION = "/SelectedGames/ScummVmAspectCorrection"
    SCUMM_VM_FULLSCREEN = "/SelectedGames/ScummVmFullscreen"
    SCUMM_VM_GAME_DATA_FOLDER_PATH = "/SelectedGames/ScummVmGameDataFolderPath"
    SCUMM_VM_GAME_TYPE = "/SelectedGames/ScummVmGameType"
    SERIES = "/SelectedGames/Series"
    SERIES_VALUES = "/SelectedGames/SeriesValues"
    SHOW_BACK = "/SelectedGames/ShowBack"
    SORT_TITLE = "/SelectedGames/SortTitle"
    SORT_TITLE_OR_TITLE = "/SelectedGames/SortTitleOrTitle"
    SOURCE = "/SelectedGames/Source"
    STAR_RATING = "/SelectedGames/StarRating"
    STAR_RATING_FLOAT = "/SelectedGames/StarRatingFloat"
    STARTUP_LOAD_DELAY = "/SelectedGames/StartupLoadDelay"
    STATUS = "/SelectedGames/Status"
    THEME_VIDEO_PATH = "/SelectedGames/ThemeVideoPath"
    TITLE = "/SelectedGames/Title"
    USE_DOS_BOX = "/SelectedGames/UseDosBox"
    USE_SCUMM_VM = "/SelectedGames/UseScummVm"
    USE_STARTUP_SCREEN = "/SelectedGames/UseStartupScreen"
    VERSION = "/SelectedGames/Version"
    VIDEO_PATH = "/SelectedGames/VideoPath"
    VIDEO_URL = "/SelectedGames/VideoUrl"
    WIKIPEDIA_ID = "/SelectedGames/WikipediaId"
    WIKIPEDIA_URL = "/SelectedGames/WikipediaUrl"
    """

    """/SelectedGameMethods"""
    ADD_NEW_ADDITIONAL_APPLICATION = "/SelectedGameMethods/AddNewAdditionalApplication"
    ADD_NEW_ALTERNATE_NAME = "/SelectedGameMethods/AddNewAlternateName"
    ADD_NEW_CUSTOM_FIELD = "/SelectedGameMethods/AddNewCustomField"
    ADD_NEW_MOUNT = "/SelectedGameMethods/AddNewMount"
    CONFIGURE = "/SelectedGameMethods/Configure"
    GET_AGGRESSIVE_WINDOW_HIDING = "/SelectedGameMethods/get_AggressiveWindowHiding"
    GET_APPLICATION_PATH = "/SelectedGameMethods/get_ApplicationPath"
    GET_BACKGROUND_IMAGE_PATH = "/SelectedGameMethods/get_BackgroundImagePath"
    GET_BACK_IMAGE_PATH = "/SelectedGameMethods/get_BackImagePath"
    GET_BOX_3D_IMAGE_PATH = "/SelectedGameMethods/get_Box3DImagePath"
    GET_BROKEN = "/SelectedGameMethods/get_Broken"
    GET_CART_3D_IMAGE_PATH = "/SelectedGameMethods/get_Cart3DImagePath"
    GET_CART_BACK_IMAGE_PATH = "/SelectedGameMethods/get_CartBackImagePath"
    GET_CART_FRONT_IMAGE_PATH = "/SelectedGameMethods/get_CartFrontImagePath"
    GET_CLEAR_LOGO_IMAGE_PATH = "/SelectedGameMethods/get_ClearLogoImagePath"
    GET_CLONE_OF = "/SelectedGameMethods/get_CloneOf"
    GET_COMMAND_LINE = "/SelectedGameMethods/get_CommandLine"
    GET_COMMUNITY_OR_LOCAL_STAR_RATING = (
        "/SelectedGameMethods/get_CommunityOrLocalStarRating"
    )
    GET_COMMUNITY_STAR_RATING = "/SelectedGameMethods/get_CommunityStarRating"
    GET_COMMUNITY_STAR_RATING_TOTAL_VOTES = (
        "/SelectedGameMethods/get_CommunityStarRatingTotalVotes"
    )
    GET_COMPLETED = "/SelectedGameMethods/get_Completed"
    GET_CONFIGURATION_COMMAND_LINE = "/SelectedGameMethods/get_ConfigurationCommandLine"
    GET_CONFIGURATION_PATH = "/SelectedGameMethods/get_ConfigurationPath"
    GET_DATE_ADDED = "/SelectedGameMethods/get_DateAdded"
    GET_DATE_MODIFIED = "/SelectedGameMethods/get_DateModified"
    GET_DETAILS_WITHOUT_PLATFORM = "/SelectedGameMethods/get_DetailsWithoutPlatform"
    GET_DETAILS_WITH_PLATFORM = "/SelectedGameMethods/get_DetailsWithPlatform"
    GET_DEVELOPER = "/SelectedGameMethods/get_Developer"
    GET_DEVELOPERS = "/SelectedGameMethods/get_Developers"
    GET_DISABLE_SHUTDOWN_SCREEN = "/SelectedGameMethods/get_DisableShutdownScreen"
    GET_DOS_BOX_CONFIGURATION_PATH = "/SelectedGameMethods/get_DosBoxConfigurationPath"
    GET_EMULATOR_ID = "/SelectedGameMethods/get_EmulatorId"
    GET_FAVORITE = "/SelectedGameMethods/get_Favorite"
    GET_FRONT_IMAGE_PATH = "/SelectedGameMethods/get_FrontImagePath"
    GET_GENRES = "/SelectedGameMethods/get_Genres"
    GET_GENRES_STRING = "/SelectedGameMethods/get_GenresString"
    GET_HIDE = "/SelectedGameMethods/get_Hide"
    GET_HIDE_ALL_NON_EXCLUSIVE_FULLSCREEN_WINDOWS = (
        "/SelectedGameMethods/get_HideAllNonExclusiveFullscreenWindows"
    )
    GET_HIDE_MOUSE_CURSOR_IN_GAME = "/SelectedGameMethods/get_HideMouseCursorInGame"
    GET_ID = "/SelectedGameMethods/get_Id"
    GET_INSTALLED = "/SelectedGameMethods/get_Installed"
    GET_LAST_PLAYED_DATE = "/SelectedGameMethods/get_LastPlayedDate"
    GET_LAUNCH_BOX_DB_ID = "/SelectedGameMethods/get_LaunchBoxDbId"
    GET_MANUAL_PATH = "/SelectedGameMethods/get_ManualPath"
    GET_MARQUEE_IMAGE_PATH = "/SelectedGameMethods/get_MarqueeImagePath"
    GET_MAX_PLAYERS = "/SelectedGameMethods/get_MaxPlayers"
    GET_MUSIC_PATH = "/SelectedGameMethods/get_MusicPath"
    GET_NOTES = "/SelectedGameMethods/get_Notes"
    GET_OVERRIDE_DEFAULT_STARTUP_SCREEN_SETTINGS = (
        "/SelectedGameMethods/get_OverrideDefaultStartupScreenSettings"
    )
    GET_PLATFORM = "/SelectedGameMethods/get_Platform"
    GET_PLATFORM_CLEAR_LOGO_IMAGE_PATH = (
        "/SelectedGameMethods/get_PlatformClearLogoImagePath"
    )
    GET_PLAY_COUNT = "/SelectedGameMethods/get_PlayCount"
    GET_PLAY_MODE = "/SelectedGameMethods/get_PlayMode"
    GET_PLAY_MODES = "/SelectedGameMethods/get_PlayModes"
    GET_PLAY_TIME = "/SelectedGameMethods/get_PlayTime"
    GET_PORTABLE = "/SelectedGameMethods/get_Portable"
    GET_PUBLISHER = "/SelectedGameMethods/get_Publisher"
    GET_PUBLISHERS = "/SelectedGameMethods/get_Publishers"
    GET_RATING = "/SelectedGameMethods/get_Rating"
    GET_RATING_IMAGE = "/SelectedGameMethods/get_RatingImage"
    GET_REGION = "/SelectedGameMethods/get_Region"
    GET_RELEASE_DATE = "/SelectedGameMethods/get_ReleaseDate"
    GET_RELEASE_TYPE = "/SelectedGameMethods/get_ReleaseType"
    GET_RELEASE_YEAR = "/SelectedGameMethods/get_ReleaseYear"
    GET_ROOT_FOLDER = "/SelectedGameMethods/get_RootFolder"
    GET_SCREENSHOT_IMAGE_PATH = "/SelectedGameMethods/get_ScreenshotImagePath"
    GET_SCUMM_VM_ASPECT_CORRECTION = "/SelectedGameMethods/get_ScummVmAspectCorrection"
    GET_SCUMM_VM_FULLSCREEN = "/SelectedGameMethods/get_ScummVmFullscreen"
    GET_SCUMM_VM_GAME_DATA_FOLDER_PATH = (
        "/SelectedGameMethods/get_ScummVmGameDataFolderPath"
    )
    GET_SCUMM_VM_GAME_TYPE = "/SelectedGameMethods/get_ScummVmGameType"
    GET_SERIES = "/SelectedGameMethods/get_Series"
    GET_SERIES_VALUES = "/SelectedGameMethods/get_SeriesValues"
    GET_SHOW_BACK = "/SelectedGameMethods/get_ShowBack"
    GET_SORT_TITLE = "/SelectedGameMethods/get_SortTitle"
    GET_SORT_TITLE_OR_TITLE = "/SelectedGameMethods/get_SortTitleOrTitle"
    GET_SOURCE = "/SelectedGameMethods/get_Source"
    GET_STAR_RATING = "/SelectedGameMethods/get_StarRating"
    GET_STAR_RATING_FLOAT = "/SelectedGameMethods/get_StarRatingFloat"
    GET_STARTUP_LOAD_DELAY = "/SelectedGameMethods/get_StartupLoadDelay"
    GET_STATUS = "/SelectedGameMethods/get_Status"
    GET_THEME_VIDEO_PATH = "/SelectedGameMethods/get_ThemeVideoPath"
    GET_TITLE = "/SelectedGameMethods/get_Title"
    GET_USE_DOS_BOX = "/SelectedGameMethods/get_UseDosBox"
    GET_USE_SCUMM_VM = "/SelectedGameMethods/get_UseScummVm"
    GET_USE_STARTUP_SCREEN = "/SelectedGameMethods/get_UseStartupScreen"
    GET_VERSION = "/SelectedGameMethods/get_Version"
    GET_VIDEO_PATH = "/SelectedGameMethods/get_VideoPath"
    GET_VIDEO_URL = "/SelectedGameMethods/get_VideoUrl"
    GET_WIKIPEDIA_ID = "/SelectedGameMethods/get_WikipediaId"
    GET_WIKIPEDIA_URL = "/SelectedGameMethods/get_WikipediaUrl"
    GET_ALL_ADDITIONAL_APPLICATIONS = (
        "/SelectedGameMethods/GetAllAdditionalApplications"
    )
    GET_ALL_ALTERNATE_NAMES = "/SelectedGameMethods/GetAllAlternateNames"
    GET_ALL_CUSTOM_FIELDS = "/SelectedGameMethods/GetAllCustomFields"
    GET_ALL_IMAGES_WITH_DETAILS = "/SelectedGameMethods/GetAllImagesWithDetails"
    GET_ALL_MOUNTS = "/SelectedGameMethods/GetAllMounts"
    GET_CONTROLLER_SUPPORT = "/SelectedGameMethods/GetControllerSupport"
    GET_EFFECTIVE_COMMAND_LINE = "/SelectedGameMethods/GetEffectiveCommandLine"
    """GET_MANUAL_PATH = "/SelectedGameMethods/GetManualPath"
    GET_MUSIC_PATH = "/SelectedGameMethods/GetMusicPath"
    GET_THEME_VIDEO_PATH = "/SelectedGameMethods/GetThemeVideoPath" """
    OPEN_FOLDER = "/SelectedGameMethods/OpenFolder"
    OPEN_MANUAL = "/SelectedGameMethods/OpenManual"
    PLAY = "/SelectedGameMethods/Play"
    """"
    GET_ALL_IMAGES_WITH_DETAILS = "/SelectedGameMethods/GetAllImagesWithDetails"
    """
    GET_BIG_BOX_DETAILS = "/SelectedGameMethods/GetBigBoxDetails"
    GET_NEW_MANUAL_FILE_PATH = "/SelectedGameMethods/GetNewManualFilePath"
    GET_NEW_MUSIC_FILE_PATH = "/SelectedGameMethods/GetNewMusicFilePath"
    GET_NEW_THEME_VIDEO_FILE_PATH = "/SelectedGameMethods/GetNewThemeVideoFilePath"
    GET_NEW_VIDEO_FILE_PATH = "/SelectedGameMethods/GetNewVideoFilePath"
    """    GET_VIDEO_PATH = "/SelectedGameMethods/GetVideoPath" """
    SET_AGGRESSIVE_WINDOW_HIDING = "/SelectedGameMethods/set_AggressiveWindowHiding"
    SET_APPLICATION_PATH = "/SelectedGameMethods/set_ApplicationPath"
    SET_BROKEN = "/SelectedGameMethods/set_Broken"
    SET_CLONE_OF = "/SelectedGameMethods/set_CloneOf"
    SET_COMMAND_LINE = "/SelectedGameMethods/set_CommandLine"
    SET_COMMUNITY_STAR_RATING = "/SelectedGameMethods/set_CommunityStarRating"
    SET_COMMUNITY_STAR_RATING_TOTAL_VOTES = (
        "/SelectedGameMethods/set_CommunityStarRatingTotalVotes"
    )
    SET_COMPLETED = "/SelectedGameMethods/set_Completed"
    SET_CONFIGURATION_COMMAND_LINE = "/SelectedGameMethods/set_ConfigurationCommandLine"
    SET_CONFIGURATION_PATH = "/SelectedGameMethods/set_ConfigurationPath"
    SET_DATE_ADDED = "/SelectedGameMethods/set_DateAdded"
    SET_DATE_MODIFIED = "/SelectedGameMethods/set_DateModified"
    SET_DEVELOPER = "/SelectedGameMethods/set_Developer"
    SET_DISABLE_SHUTDOWN_SCREEN = "/SelectedGameMethods/set_DisableShutdownScreen"
    SET_DOS_BOX_CONFIGURATION_PATH = "/SelectedGameMethods/set_DosBoxConfigurationPath"
    SET_EMULATOR_ID = "/SelectedGameMethods/set_EmulatorId"
    SET_FAVORITE = "/SelectedGameMethods/set_Favorite"
    SET_GENRES_STRING = "/SelectedGameMethods/set_GenresString"
    SET_HIDE = "/SelectedGameMethods/set_Hide"
    SET_HIDE_ALL_NON_EXCLUSIVE_FULLSCREEN_WINDOWS = (
        "/SelectedGameMethods/set_HideAllNonExclusiveFullscreenWindows"
    )
    SET_HIDE_MOUSE_CURSOR_IN_GAME = "/SelectedGameMethods/set_HideMouseCursorInGame"
    SET_INSTALLED = "/SelectedGameMethods/set_Installed"
    SET_LAST_PLAYED_DATE = "/SelectedGameMethods/set_LastPlayedDate"
    SET_LAUNCH_BOX_DB_ID = "/SelectedGameMethods/set_LaunchBoxDbId"
    SET_MANUAL_PATH = "/SelectedGameMethods/set_ManualPath"
    SET_MAX_PLAYERS = "/SelectedGameMethods/set_MaxPlayers"
    SET_MUSIC_PATH = "/SelectedGameMethods/set_MusicPath"
    SET_NOTES = "/SelectedGameMethods/set_Notes"
    SET_OVERRIDE_DEFAULT_STARTUP_SCREEN_SETTINGS = (
        "/SelectedGameMethods/set_OverrideDefaultStartupScreenSettings"
    )
    SET_PLATFORM = "/SelectedGameMethods/set_Platform"
    SET_PLAY_COUNT = "/SelectedGameMethods/set_PlayCount"
    SET_PLAY_MODE = "/SelectedGameMethods/set_PlayMode"
    SET_PLAY_TIME = "/SelectedGameMethods/set_PlayTime"
    SET_PORTABLE = "/SelectedGameMethods/set_Portable"
    SET_PUBLISHER = "/SelectedGameMethods/set_Publisher"
    SET_RATING = "/SelectedGameMethods/set_Rating"
    SET_REGION = "/SelectedGameMethods/set_Region"
    SET_RELEASE_DATE = "/SelectedGameMethods/set_ReleaseDate"
    SET_RELEASE_TYPE = "/SelectedGameMethods/set_ReleaseType"
    SET_RELEASE_YEAR = "/SelectedGameMethods/set_ReleaseYear"
    SET_ROOT_FOLDER = "/SelectedGameMethods/set_RootFolder"
    SET_SCUMM_VM_ASPECT_CORRECTION = "/SelectedGameMethods/set_ScummVmAspectCorrection"
    SET_SCUMM_VM_FULLSCREEN = "/SelectedGameMethods/set_ScummVmFullscreen"
    SET_SCUMM_VM_GAME_DATA_FOLDER_PATH = (
        "/SelectedGameMethods/set_ScummVmGameDataFolderPath"
    )
    SET_SCUMM_VM_GAME_TYPE = "/SelectedGameMethods/set_ScummVmGameType"
    SET_SERIES = "/SelectedGameMethods/set_Series"
    SET_SHOW_BACK = "/SelectedGameMethods/set_ShowBack"
    SET_SORT_TITLE = "/SelectedGameMethods/set_SortTitle"
    SET_SOURCE = "/SelectedGameMethods/set_Source"
    SET_STAR_RATING = "/SelectedGameMethods/set_StarRating"
    SET_STAR_RATING_FLOAT = "/SelectedGameMethods/set_StarRatingFloat"
    SET_STARTUP_LOAD_DELAY = "/SelectedGameMethods/set_StartupLoadDelay"
    SET_STATUS = "/SelectedGameMethods/set_Status"
    SET_THEME_VIDEO_PATH = "/SelectedGameMethods/set_ThemeVideoPath"
    SET_TITLE = "/SelectedGameMethods/set_Title"
    SET_USE_DOS_BOX = "/SelectedGameMethods/set_UseDosBox"
    SET_USE_SCUMM_VM = "/SelectedGameMethods/set_UseScummVm"
    SET_USE_STARTUP_SCREEN = "/SelectedGameMethods/set_UseStartupScreen"
    SET_VERSION = "/SelectedGameMethods/set_Version"
    SET_VIDEO_PATH = "/SelectedGameMethods/set_VideoPath"
    SET_VIDEO_URL = "/SelectedGameMethods/set_VideoUrl"
    SET_WIKIPEDIA_ID = "/SelectedGameMethods/set_WikipediaId"
    SET_WIKIPEDIA_URL = "/SelectedGameMethods/set_WikipediaUrl"
    TRY_REMOVE_ADDITIONAL_APPLICATION = (
        "/SelectedGameMethods/TryRemoveAdditionalApplication"
    )
    TRY_REMOVE_ALTERNATE_NAMES = "/SelectedGameMethods/TryRemoveAlternateNames"
    TRY_REMOVE_CUSTOM_FIELD = "/SelectedGameMethods/TryRemoveCustomField"
    TRY_REMOVE_MOUNT = "/SelectedGameMethods/TryRemoveMount"
    UPDATE_TITLE_AND_MIGRATE_MEDIA = "/SelectedGameMethods/UpdateTitleAndMigrateMedia"

    """/PlayGame"""
    PLAY_GAME_TITLE = "/PlayGame/Title"
    PLAY_GAME_PUBLISHER_AND_TITLE = "/PlayGame/PublisherAndTitle"
    PLAY_GAME_ID = "/PlayGame/LaunchBoxDbId"

    """/Game"""
    GAME_TITLE = "/Game/Title"
    GAME_PUBLISHER_AND_TITLE = "/Game/PublisherAndTitle"
    GAME_ID = "/Game/LaunchBoxDbId"

    """/GetAllGames"""
    GET_ALL_GAMES = "/GetAllGames"

    """/GetAllPlatforms"""
    GET_ALL_PLATFORMS = "/GetAllPlatforms"

    """/Platform"""
    PLATFORM_TITLE = "/Platform/Title" """/IncludeGameInfo"""

    """/Binary"""
    SCREENSHOT_IMAGE = "/Binary/ScreenshotImage"
    FRONT_IMAGE = "/Binary/FrontImage"
    MARQUEE_IMAGE = "/Binary/MarqueeImage"
    BACK_IMAGE = "/Binary/BackImage"
    BOX_3D_IMAGE = "/Binary/Box3DImage"
    BACKGROUNBD_IMAGE = "/Binary/BackgroundImage"
    CART_3D_IMAGE = "/Binary/Cart3DImage"
    CART_FRONT_IMAGE = "/Binary/CartFrontImage"
    CART_BACK_IMAGE = "/Binary/CartBackImage"
    CLEAR_LOGO_IMAGE = "/Binary/ClearLogoImage"
    PLATFORM_CLEAR_LOGO_IMAGE = "/Binary/PlatformClearLogoImage"
    APPLICATION = "/Binary/Application"
    CONFIGURATION = "/Binary/Configuration"
    DOSBOX_CONFIGURATION = "/Binary/DosBoxConfiguration"
    MANUAL = "/Binary/Manual"
    MUSIC = "/Binary/Music"
    SCUMM_VM_GAME_DATA_FOLDER = "/Binary/ScummVmGameDataFolder"
    VIDEO = "/Binary/Video"
    THEME_VIDEO = "/Binary/ThemeVideo"

    """/Manual"""
    API_MANUAL = "/Manual"

    """/Image"""
    IMAGE_SCREENSHOT = "/Image/Screenshot"
    IMAGE_FRONT = "/Image/Front"
    IMAGE_MARQUEE = "/Image/Marquee"
    IMAGE_BACK = "/Image/Back"
    IMAGE_BOX_3D = "/Image/Box3D"
    IMAGE_BACKGROUND = "/Image/Background"
    IMAGE_CART_3D = "/Image/Cart3D"
    IMAGE_CART_FRONT = "/Image/CartFront"
    IMAGE_CART_BACK = "/Image/CartBack"
    IMAGE_CLEAR_LOGO = "/Image/ClearLogo"
    IMAGE_PLATFORM_CLEAR_LOGO = "/Image/PlatformClearLogo"
